export const SEARCH_FOCUS = 'header/search-focus'
export const SEARCH_BLUR = 'header/search-blur'
export const SET_TRENDING_LIST = 'header/set-trending-list'
export const SET_MOUSE_STATUS = 'header/set-mouse-status'
export const SWITCH_PAGE = 'header/switch-page'
export const SET_TREND_TOTAL = 'header/set-trend-total'
